game: trading
# 2 modes: "money-gone" and "money-not-gone"
mode: money-gone
competitors:
  - name: IBuyEverything
    image: js-test-competitor:buyer
  - name: Company7
    image: js-test-competitor:test
  - js-test-competitor:random
  - js-test-competitor:randomprinter
